import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="flex flex-row w-full min-h-screen overflow-x-hidden">
        <div className='flex-none drawer-contianer w-60 bg-black text-white'> sidebar content here</div>
        {children}
        </body>
    </html>
  )
}
